apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resilience-lab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kmuschallik/k3s_aws.git
    targetRevision: HEAD
    path: kustomize/overlays/aws
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
